### ISSUE TITLE
[Request] Add icon for all live badges

### ISSUE THREAD

**Issue by GMartigny** [badgen/badgen-icons#11]
Hi,

Badgen support a large variety of live badges. It would be cool to have an icon for each of those live services. Of course, icons should be easily accessible in SVG format.

For example, PackagePhobia has a [pretty clean SVG logo](https://packagephobia.now.sh/logo.svg) available.

If this align with your view, I'll be glad to help by opening PRs.

**Comment by amio** [comment]
I guess not all service has an icon, but if it has, it would be nice to have it in `badgen-icons`. Thanks @GMartigny for helping on this!
