### ISSUE TITLE
Add PayPal icon

### ISSUE THREAD

**Issue by tunnckoCore** [badgen/badgen-icons#16]
It's a bit tricky for this icon i think.

But here are some https://icons8.com/icons/set/paypal

Or maybe ![](https://img.icons8.com/android/24/c3c3c3/paypal.png)

```
https://img.icons8.com/android/24/ffffff/paypal.png
```

**Comment by tunnckoCore** [comment]
Or probably

https://badgen.net/badge/paypal/donation/003087?icon=https://svgshare.com/i/Drk.svg

![](https://badgen.net/badge/paypal/donation/003087?icon=https://svgshare.com/i/Drk.svg)

**Comment by amio** [comment]
https://simpleicons.now.sh/ is for this

https://badgen.net/badge/paypal/donation/003087?icon=https://simpleicons.now.sh/paypal/fff
![](https://badgen.net/badge/paypal/donation/003087?icon=https://simpleicons.now.sh/paypal/fff)

**Comment by tunnckoCore** [comment]
Oh yea, we forgot that, haha.

Maybe would be good to have it by default. It's quite popular.
