### ISSUE TITLE
Support RunKit url instead of id

### ISSUE THREAD

**Issue by riccardoporreca** [badgen/badgen-icons#25]
RunKit endpoints are supported by specifying their id, e.g. 
`https://badgen.net/runkit/cal-badge-icd0onfvrxx6/Asia/Shanghai`
for https://runkit.com/amio/cal-badge.

It could beconvenient to instead specify the URL of the endpoint (the "endpoint" link in RunKit), like https://runkit.io/amio/cal-badge/0.0.0 or https://runkit.io/amio/cal-badge/branches/master
`https://badgen.net/runkit/amio/cal-badge/0.0.0/Asia/Shanghai`
`https://badgen.net/runkit/amio/cal-badge/branches/master/Asia/Shanghai`

It is on the one hand more explicit, and on the other I am not sure whether the id stays the same when e.g. the `master` branch changes, so that one can change the endpoint definition w/o changing the badge URL.

Of course the alternative is to use 
`https://badgen.net/https/runkit.io/amio/cal-badge/branches/master/Asia/Shanghai`

**Comment by amio** [comment]
We would need two more scheme to support it:
- `/runkit-xxx/:name/:version/:args+`
- `/runkit-yyy/:name/branches/:branch/:args+`

Thus I would recommend the alternative method you have mentioned:
`https://badgen.net/https/runkit.io/amio/cal-badge/branches/master/Asia/Shanghai`

It's 6 more chars (`/https`), but in return we can keep url schemes simple, I like it 😋

**Comment by riccardoporreca** [comment]
Fully Agree in the end :)
