### ISSUE TITLE
Allow other options in the endpoint

### ISSUE THREAD

**Issue by riccardoporreca** [badgen/badgen-icons#26]
It would be great to support other [badge options](https://badgen.net/#options) in the endpoint JSON response. Only `subject`, `status` and `color` seem to be supported.

**Comment by amio** [comment]
The json response is deprecated, since we are running out of GitHub api rate limit 😔

Or do you mean some other JSON response? @riccardoporreca

**Comment by riccardoporreca** [comment]
I am talking about the JSON response from an HTTPS endpoint (https://badgen.net/https).
**I hope this is something you still plan to support, can you please comment on this?**

I can tell you where I am coming from: I have been using shields.io with a RunKit endpoint, and shields.io allows the endpoint to return anything you would normally pass as query in the URL (e.g. `labelColor`), which would be used to style the badge.

I have switched to badgen.net due a very poor and strange performance issue / broken badges with shields.io (somewhat related to getting the badge from a browser, i can still `curl` the URL in a decent way, very weird to me), and was initially using the same endpoint, which would also return a `labelColor`,  which however badgen.net would ignore.

After looking more into this, it is probably a good design principle to just allow `subject`, `status` and `color` do be defined in the endpoint, so you can probably ignore this.

And by the way, thanks a lot for the wonderful project!

**Comment by riccardoporreca** [comment]
@amio, I am very sorry to have opened this issue in the wrong repo! It of course belongs to https://github.com/badgen/badgen.net/

Apologies for the confusion

**Comment by amio** [comment]
Yep, that's fine :) @riccardoporreca
